name: evit-unet
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scikit-image
  - tensorboardx
  - pip
  - pip:
      - tqdm
      - opencv-python
      - timm
      - grad-cam
      - efficientnet-pytorch
      - dominate
      - pyyaml
      - ttach
      - medpy
      - seaborn
      - segmentation-mask-overlay
      - thop
      - h5py
      - batchgenerators

